# Generated by Django 4.2.4 on 2023-09-02 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_comment_date_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 6, 10, 32, 250002, tzinfo=datetime.timezone.utc)),
        ),
    ]
